import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: "#fff" },
    header: { flexDirection: "row", alignItems: "center", paddingHorizontal: 16, paddingTop: 12, paddingBottom: 8 },
    backBtn: { padding: 8, borderRadius: 20, backgroundColor: "#f2f2f2" },
    title: { fontSize: 18, fontWeight: "700", marginLeft: 12 },
    body: { flex: 1, padding: 16 },
    sectionTitle: { fontSize: 16, fontWeight: "700", marginBottom: 8 },
    list: { maxHeight: 220, marginBottom: 12 },
    row: { flexDirection: "row", alignItems: "center", paddingVertical: 8 },
    itemName: { fontSize: 15, fontWeight: "600" },
    itemQty: { color: "#666", marginTop: 4 },
    itemPrice: { fontSize: 14, fontWeight: "700" },
    sep: { height: 1, backgroundColor: "#eee" },
    summary: { marginTop: 12, paddingTop: 12, borderTopWidth: 1, borderTopColor: "#f0f0f0" },
    summaryRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 8 },
    summaryLabel: { color: "#666" },
    summaryValue: { fontWeight: "700" },
    totalValue: { fontSize: 16 },
    locationRow: { marginTop: 12 },
    locationLabel: { color: "#666", marginBottom: 4 },
    locationText: { color: "#333", fontWeight: "600" },
    placeBtn: { marginTop: 16, backgroundColor: "#FF6B00", paddingVertical: 14, borderRadius: 10, alignItems: "center" },
    placeBtnText: { color: "#fff", fontWeight: "700" },
    disabledBtn: { opacity: 0.6 },
    empty: { alignItems: "center", paddingVertical: 24 },
    emptyText: { color: "#666" },
});
